apiVersion: v1
kind: Pod
metadata:
  name: kube-proxy
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: kube-proxy
    image: gcr.io/google_containers/hyperkube:{{ kube_version }}
    command:
    - /hyperkube
    - proxy
    - --master=http://127.0.0.1:8080
    - --v={{kube_log_level}}
    - --proxy-port-range={{ proxy_port_range }}
    - --proxy-mode={{ proxy_mode }}
    securityContext:
      privileged: true
