apiVersion: v1
kind: ReplicationController
metadata:
  name: heapster-v10
  namespace: kube-system
  labels:
    k8s-app: heapster
    version: v10
    kubernetes.io/cluster-service: "true"
spec:
  replicas: 1
  selector:
    k8s-app: heapster
    version: v10
  template:
    metadata:
      labels:
        k8s-app: heapster
        version: v10
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccount: "heapster"
      containers:
#        - image: gcr.io/google_containers/heapster:v0.18.2
        - image: gcr.io/google_containers/heapster:v1.1.0
          name: heapster
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
          command:
            - /heapster
            - -source=kubernetes:https://{{ inventory_hostname }}:443?inClusterConfig=false&useServiceAccount=true&auth=&insecure=true
            - -sink=influxdb:http://monitoring-influxdb:8086
            - -tls_cert=/etc/kubernetes/ssl/kubelet.crt 
            - -tls_client_ca=/etc/kubernetes/ssl/ca.crt 
            - -tls_key=/etc/kubernetes/ssl/kubelet.key
#            - --source=kubernetes:''
#            - --sink=influxdb:http://monitoring-influxdb:8086
#            - --stats_resolution=10s
#            - --sink_frequency=10s
          volumeMounts:
            - name: etc-kubernetes-ssl
              mountPath: /etc/kubernetes/ssl
      volumes:
        - name: etc-kubernetes-ssl
          hostPath:
            path: /etc/kubernetes/ssl

